highlighter: rouge

title: caspo
description: Reasoning on the response of logical signaling networks with Answer Set Programming
google_analytics: UA-37294887-1
show_downloads: true
theme: jekyll-theme-cayman